/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum fluid_types {
  FLUID_TYPE_PURE,
  FLUID_TYPE_PSEUDOPURE,
  FLUID_TYPE_REFPROP,
  FLUID_TYPE_INCOMPRESSIBLE_LIQUID,
  FLUID_TYPE_INCOMPRESSIBLE_SOLUTION
}
